name: Build tagged Alpine images

on:
  push:
    tags: ["alpine-*"]

env:
  OS: alpine
  DOCKER_REPO: ilyes512/php74-fpm

jobs:
  build_tagged_alpine:
    name: Build tagged Alpine
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set TAG-env
        run: echo ::set-env name=TAG::$(echo $GITHUB_REF | cut -d / -f 3-)
      - name: Output TAG-env
        run: 'echo "\$TAG: $TAG"'
      - uses: docker/build-push-action@v2
        with:
          repository: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          dockerfile: ${{ env.OS }}/Dockerfile
          target: builder
          add_git_labels: true
          tag: ${{ env.TAG }}-builder
      - uses: docker/build-push-action@v2
        with:
          repository: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          dockerfile: ${{ env.OS }}/Dockerfile
          target: runtime
          add_git_labels: true
          tag: ${{ env.TAG }}-runtime
