name: Test Building Alpine images

on:
  pull_request:
    paths: ["alpine/**"]

env:
  OS: alpine
  DOCKER_REPO: ilyes512/php74-fpm

jobs:
  test_build:
    name: Test Build Alpine
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          repository: ${{ env.DOCKER_REPO }}
          add_git_labels: true
          dockerfile: ${{ env.OS }}/Dockerfile
          target: builder
          tag: ${{ env.OS }}-pr-builder
          push: false
      - uses: docker/build-push-action@v2
        with:
          repository: ${{ env.DOCKER_REPO }}
          add_git_labels: true
          dockerfile: ${{ env.OS }}/Dockerfile
          target: runtime
          tag: ${{ env.OS }}-pr-runtime
          push: false
